core/src/test/resources/org/jboss/pnc/causeway/pncclient/product-release-distributed-build-records-ids-1.json
pom.xml

update pnc version to 0.10-SNAPSHOT
update jhttpc version to 1.2
update intergration test json data to match current pnc model

update pnc version to 0.10-SNAPSHOT

---

README.md
core/src/test/java/org/jboss/pnc/causeway/pncclient/PncClientIT.java
launcher/src/main/conf/main.conf
product-release-1-distributed-build-records-ids.json
product-release-1.json

update pnc url for intergration tests
remove files commited by mistake

update pnc url for intergration tests

---

application/src/main/conf/main.conf
core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/config/CausewayConfig.java

@jbrazdil I hope I understood your intention correctly ...

Fixed small bug (error in construction of koji web url).

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
core/src/test/resources/org/jboss/pnc/causeway/brewclient/build-records-61-1.json

The version was parsed to NVR and taken from it. Instead of parsing it
back, I used original data.

Fix for wrong maven version

---

web/src/main/webapp/WEB-INF/web.xml

[v1.4][NCL-4236] Allow any authenticated user to do some stuff

---

core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java

There was an issue where if the error being captured while importing a
build / untagging a build was an exception where the 'getMessage()'
method call returns null, then the REST response is not sent back.
This is because we fail a 'NotNull' validation while building the
response because the log field is null (log field is filled with
`exception.getMessage()`).
This commit fixes it by:
1. checking if `getMessage()` is not-null. If not-null, use it for
'log'. Else:
2. include the stacktrace in the exception log so as to provide more
context on where the exception was thrown.

[v1.4][NCL-4384] Report errors back no matter what

---

core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java

There was an issue where if the error being captured while importing a
build / untagging a build was an exception where the 'getMessage()'
method call returns null, then the REST response is not sent back.
This is because we fail a 'NotNull' validation while building the
response because the log field is null (log field is filled with
`exception.getMessage()`).
This commit fixes it by:
1. checking if `getMessage()` is not-null. If not-null, use it for
'log'. Else:
2. include the stacktrace in the exception log so as to provide more
context on where the exception was thrown.

[NCL-4384] Report errors back no matter what

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslator.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/ctl/PncImportControllerImpl.java
rest/src/main/java/org/jboss/pnc/causeway/rest/model/MavenBuild.java

[NCL-4401] Update Causeway to guess MEAD version when missing in data

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java

[1.4][NCL-4382] workaround NPE while capturing import errors

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java

[NCL-4382] workaround NPE while capturing import errors

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClient.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java
core/src/test/java/org/jboss/pnc/causeway/ctl/ImportControllerTest.java

[NCL-4710] Bump revision number when build is being reimported.

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClient.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/ctl/PncImportControllerImpl.java
core/src/test/java/org/jboss/pnc/causeway/ctl/ImportControllerTest.java
core/src/test/java/org/jboss/pnc/causeway/ctl/PncImportControllerTest.java

Fix tagging build with bumped revision

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
core/src/main/java/org/jboss/pnc/causeway/pncclient/model/BuildRecordRest.java
pom.xml
rest/src/main/java/org/jboss/pnc/causeway/rest/model/Build.java
rest/src/main/java/org/jboss/pnc/causeway/rest/model/MavenBuild.java

[NCL-4653] Add optional scmTag extra field when importing to Brew

---

rest/src/main/java/org/jboss/pnc/causeway/rest/pnc/BuildImportResultRest.java

[NCL-4867] brewPush failing with NullPointerException

---

core/src/main/java/org/jboss/pnc/causeway/ctl/PncImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/pncclient/model/ArtifactRest.java

[NCL-4867] Don't import DELETED artifacts

---

core/src/main/java/org/jboss/pnc/causeway/ctl/ImportController.java
core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java
core/src/test/java/org/jboss/pnc/causeway/ctl/ImportControllerTest.java
rest/src/main/java/org/jboss/pnc/causeway/rest/model/BuildImportRequest.java
web/src/main/java/org/jboss/pnc/causeway/rest/ImportEndpoint.java

[NCL-4799] Add flag for build reimporting

---

core/src/main/java/org/jboss/pnc/causeway/ctl/PncImportControllerImpl.java

[NCL-4867] Do not try to tag not imported build

---

core/pom.xml
metrics/pom.xml
pom.xml
rest/pom.xml
web/pom.xml

[NCL-4937] Update to EAP 7.2.2 with JDK 11

---

pom.xml

Pom Repo FIX

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/ImportFileGenerator.java
core/src/main/java/org/jboss/pnc/causeway/config/CausewayConfig.java
core/src/main/java/org/jboss/pnc/causeway/pncclient/PncClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/util/MDCUtils.java
web/src/main/java/org/jboss/pnc/causeway/rest/filter/MDCLoggingFilter.java

[NCL-5069] Pass Log context to Indy

---

core/pom.xml
pom.xml

Use orch rest-client instead of rest-api

---

core/src/main/java/org/jboss/pnc/causeway/bpmclient/BPMClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/ImportFileGenerator.java
core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/ctl/PncImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/inject/CausewayProducer.java
web/src/main/java/org/jboss/pnc/causeway/rest/filter/MDCLoggingFilter.java

[NCL-4426] Improve logging messages

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslator.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/ImportFileGenerator.java
core/src/main/java/org/jboss/pnc/causeway/config/CausewayConfig.java
core/src/main/java/org/jboss/pnc/causeway/ctl/PncImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/inject/CausewayProducer.java
core/src/main/java/org/jboss/pnc/causeway/pncclient/BuildArtifacts.java
core/src/main/java/org/jboss/pnc/causeway/pncclient/PncClientImpl.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/ImportFileGeneratorTest.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/TranslatorTest.java
core/src/test/java/org/jboss/pnc/causeway/ctl/ImportControllerTest.java
core/src/test/java/org/jboss/pnc/causeway/ctl/PncImportControllerTest.java
eclipse-codeStyle.xml
rest/src/main/java/org/jboss/pnc/causeway/rest/BrewBuild.java
rest/src/main/java/org/jboss/pnc/causeway/rest/CallbackTarget.java
rest/src/main/java/org/jboss/pnc/causeway/rest/model/Build.java
rest/src/main/java/org/jboss/pnc/causeway/rest/model/BuiltArtifact.java
rest/src/main/java/org/jboss/pnc/causeway/rest/model/MavenBuild.java
rest/src/main/java/org/jboss/pnc/causeway/rest/model/MavenBuiltArtifact.java
rest/src/main/java/org/jboss/pnc/causeway/rest/model/NpmBuild.java
rest/src/main/java/org/jboss/pnc/causeway/rest/model/NpmBuiltArtifact.java
web/src/main/java/org/jboss/pnc/causeway/rest/PncImportResourceEndpoint.java

[NCL-1810] Apply update to eclipse codestyle

---

core/src/main/java/org/jboss/pnc/causeway/CausewayException.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClient.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslator.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/ImportFileGenerator.java
core/src/main/java/org/jboss/pnc/causeway/config/CausewayConfig.java
core/src/main/java/org/jboss/pnc/causeway/config/CausewayConfigurator.java
core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/ctl/PncImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/inject/CausewayProducer.java
core/src/main/java/org/jboss/pnc/causeway/pncclient/BuildArtifacts.java
core/src/main/java/org/jboss/pnc/causeway/pncclient/PncClientImpl.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/ImportFileGeneratorTest.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/TranslatorTest.java
core/src/test/java/org/jboss/pnc/causeway/ctl/ImportControllerTest.java
core/src/test/java/org/jboss/pnc/causeway/ctl/PncImportControllerTest.java
eclipse-codeStyle.xml
rest/src/main/java/org/jboss/pnc/causeway/rest/BrewBuild.java
rest/src/main/java/org/jboss/pnc/causeway/rest/CallbackTarget.java
rest/src/main/java/org/jboss/pnc/causeway/rest/model/Build.java
rest/src/main/java/org/jboss/pnc/causeway/rest/model/BuiltArtifact.java
rest/src/main/java/org/jboss/pnc/causeway/rest/model/MavenBuild.java
rest/src/main/java/org/jboss/pnc/causeway/rest/model/MavenBuiltArtifact.java
rest/src/main/java/org/jboss/pnc/causeway/rest/model/NpmBuild.java
rest/src/main/java/org/jboss/pnc/causeway/rest/model/NpmBuiltArtifact.java
web/src/main/java/org/jboss/pnc/causeway/rest/PncImportResourceEndpoint.java
web/src/main/java/org/jboss/pnc/causeway/rest/UserService.java

[NCL-1810] Use new format

---

core/src/main/java/org/jboss/pnc/causeway/CausewayException.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClient.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslator.java
core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/pncclient/PncClientImpl.java
eclipse-codeStyle.xml

[NCL-1810] 120 length line comment

---

eclipse-codeStyle.xml
rest/src/main/java/org/jboss/pnc/causeway/rest/pnc/BuildImportStatus.java

[NCL-1810] Properly format enums

---

pom.xml

Align POM to other PNC projects

---

core/src/main/java/org/jboss/pnc/causeway/CausewayFailure.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/ctl/PncImportControllerImpl.java
core/src/test/java/org/jboss/pnc/causeway/ctl/ImportControllerTest.java
core/src/test/java/org/jboss/pnc/causeway/ctl/PncImportControllerTest.java
rest/src/main/java/org/jboss/pnc/causeway/rest/pnc/BuildImportResultRest.java

[NCL-5706][NCL-5735] Remove ArtifactImportError, but log the error

---

eclipse-codeStyle.xml

[NCLSUP-94] Properly format array initializers

---

core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/ctl/PncImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/util/MDCUtils.java

Add buildId MDC context to the causeway logs

---

rest/src/main/java/org/jboss/pnc/causeway/rest/pnc/MilestoneReleaseResultRest.java

Return correct eventType in milestone release result.

---

core/src/main/java/org/jboss/pnc/causeway/bpmclient/BPMClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/ctl/PncImportControllerImpl.java
core/src/test/java/org/jboss/pnc/causeway/ctl/PncImportControllerTest.java
rest/src/main/java/org/jboss/pnc/causeway/rest/pnc/MilestoneReleaseResultRest.java
rest/src/main/java/org/jboss/pnc/causeway/rest/pnc/ReleaseStatus.java

Related: https://github.com/project-ncl/pnc/pull/3248

[NCL-5940] Fix handling of error response to Milestone Brew Push

---

rest/src/main/java/org/jboss/pnc/causeway/rest/model/Build.java

[NCLSUP-110] Don't require buildVersion to be set

---

core/src/main/java/org/jboss/pnc/causeway/bpmclient/BPMClient.java
core/src/main/java/org/jboss/pnc/causeway/bpmclient/BPMClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/ctl/PncImportControllerImpl.java
core/src/test/java/org/jboss/pnc/causeway/ctl/PncImportControllerTest.java

[NCL-6141] Use the callback headers and method info for callback

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslator.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
pom.xml

[NCL-6319] Modify Causeway to handle the new SBT build type

---

core/src/main/java/org/jboss/pnc/causeway/source/SourceRenamer.java

Fix mark not supported when reading response streams

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
core/src/main/java/org/jboss/pnc/causeway/source/RenamedSources.java
core/src/main/java/org/jboss/pnc/causeway/source/SourceRenamer.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/ImportFileGeneratorTest.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/TranslatorTest.java

Fix wrong type of the sources archive

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
core/src/main/java/org/jboss/pnc/causeway/source/RenamedSources.java
core/src/main/java/org/jboss/pnc/causeway/source/SourceRenamer.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/ImportFileGeneratorTest.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/TranslatorTest.java
pom.xml

[NCL-6324] use remote-source-file BType for sources

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/TranslatorTest.java

[NCL-6494] Fix push of NPM packages

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClient.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/ImportFileGenerator.java
core/src/main/java/org/jboss/pnc/causeway/ctl/PncImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/pncclient/BuildArtifacts.java
core/src/main/java/org/jboss/pnc/causeway/pncclient/PncClient.java
core/src/main/java/org/jboss/pnc/causeway/pncclient/PncClientImpl.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/ImportFileGeneratorTest.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/TranslatorTest.java
core/src/test/java/org/jboss/pnc/causeway/ctl/PncImportControllerTest.java
rest/src/main/java/org/jboss/pnc/causeway/rest/pnc/BuildImportResultRest.java

[NCL-6632] Use string IDs of orch entities

---

pom.xml

Update kojiji versions and pnc-api and rest-client

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/ImportFileGenerator.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/ImportFileGeneratorTest.java

[NCL-6646] Don't call HEAD to get artifact size

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslator.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/ImportFileGenerator.java
core/src/main/java/org/jboss/pnc/causeway/ctl/PncImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/source/SourceRenamer.java
core/src/test/java/org/jboss/pnc/causeway/source/SourceRenamerTest.java

[NCL-6659] Check if sources exist before generating them

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java

Fix possible NPE when build version is not provided

---

core/src/main/java/org/jboss/pnc/causeway/ctl/PncImportControllerImpl.java
core/src/test/java/org/jboss/pnc/causeway/ctl/PncImportControllerTest.java
core/src/test/java/org/jboss/pnc/causeway/source/SourceRenamerTest.java

[NCLSUP-419] fix mileston import sources archive clash

---

core/src/main/java/org/jboss/pnc/causeway/pncclient/PncClientImpl.java

[NCL-6803] Improve error handling when sources can't be downloaded

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
core/src/main/java/org/jboss/pnc/causeway/source/RenamedSources.java
core/src/main/java/org/jboss/pnc/causeway/source/SourceRenamer.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/ImportFileGeneratorTest.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/TranslatorTest.java

[NCL-6937] Change Koji type of generated sources - use type of the built artifacts

---

.gitignore
core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/TranslatorTest.java
core/src/test/java/org/jboss/pnc/causeway/ctl/PncImportControllerTest.java
core/src/test/resources/org/jboss/pnc/causeway/brewclient/build-dto-npm.json
pom.xml

[NCL-6494] Fix NPM Brew push by bumping kojiji version

---

core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java

Test use of logging marker

---

pom.xml

[Devel] Upgrade to J11 compiler

---

core/src/main/java/org/jboss/pnc/causeway/ErrorMessages.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/ImportFileGenerator.java
core/src/main/java/org/jboss/pnc/causeway/config/CausewayConfig.java
core/src/main/java/org/jboss/pnc/causeway/config/CausewayConfigurator.java
core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/ctl/PncImportControllerImpl.java
core/src/main/java/org/jboss/pnc/causeway/inject/CausewayProducer.java
core/src/main/java/org/jboss/pnc/causeway/pncclient/PncClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/source/RenamedSources.java
core/src/main/java/org/jboss/pnc/causeway/source/SourceRenamer.java
core/src/test/java/org/jboss/pnc/causeway/ctl/ImportControllerTest.java
core/src/test/java/org/jboss/pnc/causeway/ctl/PncImportControllerTest.java

[NCL-7242] Extract error messages to class with static message creator methods

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java

[NCL-6666] Validate proper tools are set

---

core/src/main/java/org/jboss/pnc/causeway/ErrorMessages.java

Use just exception toString in error messages to handle null messages

---

.gitignore
core/src/main/java/org/jboss/pnc/causeway/bpmclient/BPMClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/pncclient/PncClientImpl.java

[NCL-7302] - Causeway: log events of interest to Splunk

---

pom.xml

[NCL-7334] - Remove classloading issues with duplicate imported dependencies

---

pom.xml

[NCL-7334] - Exclude import of opentelemetry-api to avoid a classloading issue on ear

---

application/pom.xml
core/pom.xml
pom.xml
rest/pom.xml
web/pom.xml

Set version to 2.5.0-SNAPSHOT

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
core/src/main/java/org/jboss/pnc/causeway/config/CausewayConfig.java

[NCL-7640] Add ignore list for tools

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/ExternalLogImportFileGenerator.java

Add residrect for log downloads

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/ExternalLogImportFileGenerator.java

Don't trust provided log size, compute it ourselves

---

core/src/main/java/org/jboss/pnc/causeway/ErrorMessages.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslator.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/SpecialImportFileGenerator.java
core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/ImportFileGeneratorTest.java
core/src/test/java/org/jboss/pnc/causeway/brewclient/TranslatorTest.java
core/src/test/java/org/jboss/pnc/causeway/ctl/ImportControllerTest.java

Hotfix the manifest to contain proper log size, caller reports bad one

---

pom.xml

[v2.5.x] Bump deps versions

---

application/pom.xml
core/pom.xml
pom.xml
rest/pom.xml
web/pom.xml

Fix release 2.5.0

---

pom.xml

This contains a bug-fix for when getting information about an NPM package in Brew

[v2.5.x][MMENG-3726] Update kojiji to 2.19

---

pom.xml

This is required for a bug-fix on getting information about NPM package in Brew

[v2.4.x][MEMNG-3726] Use kojiji 2.19

---

web/src/main/webapp/WEB-INF/web.xml

This is for HTTP methods:
- DELETE
- PUT
- TRACE
- POST
Moreover, the `/rest/untag/build` needs a specific role to be used ("system-user")

[NCLSUP-960] Re-add authentication and authorization

---

web/src/main/webapp/WEB-INF/web.xml

This is for HTTP methods:
- DELETE
- PUT
- TRACE
- POST
Moreover, the `/rest/untag/build` needs a specific role to be used ("system-user")

[v2.5][NCLSUP-960] Re-add authentication and authorization

---

web/src/main/webapp/WEB-INF/web.xml

The role name is: pnc-users-causeway-admin

[NCL-8148] All non-GET endpoints require role

---

pom.xml

Mark it as provided in the pom.xml

keycloak-authz-client already provided by sso adapter

---

pom.xml

Try to specify httpclient as provided

---

application/src/main/application/META-INF/jboss-deployment-structure.xml
pom.xml

Use keycloak libraries from EAP deployment

---

README.md
application/src/main/application/META-INF/jboss-deployment-structure.xml
core/pom.xml
core/src/main/java/org/jboss/pnc/causeway/authentication/KeycloakClient.java
core/src/main/java/org/jboss/pnc/causeway/authentication/KeycloakClientException.java
core/src/main/java/org/jboss/pnc/causeway/config/CausewayConfig.java
core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java
core/src/test/java/org/jboss/pnc/causeway/ctl/ImportControllerTest.java
pom.xml
web/src/main/webapp/WEB-INF/web.xml

PNC 2.6 backport

---

web/src/main/webapp/WEB-INF/web.xml

This reverts commit 9523aceac80b15a7239dc7baa2e60f2a6ed64bcd.

Revert "[NCL-8148] All non-GET endpoints require role (#209)"

---

web/src/main/webapp/WEB-INF/web.xml

The role name is: pnc-users-causeway-admin

[v2.6.x][NCL-8148] All non-GET endpoints require role (#209)

---

pom.xml

Fix keycloak version

---

core/src/main/java/org/jboss/pnc/causeway/bpmclient/BPMClientImpl.java
pom.xml

[v2.6] Add auth headers to BPM callback too 

---

core/src/main/java/org/jboss/pnc/causeway/bpmclient/BPMClientImpl.java

Also bump atlas-npm-identities version to 1.1.3 because otherwise it doesn't compile.

Add auth headers to BPM callback too

---

web/src/main/webapp/WEB-INF/web.xml

[NCL-8147] Rename role to pnc-app-causeway-user

---

web/src/main/java/org/jboss/pnc/causeway/rest/Root.java

[NCL-6708] Specify REST path of version

---

web/pom.xml
web/src/main/java/org/jboss/pnc/causeway/rest/JacksonProvider.java

[NCL-6708] Add Jackson provider to serialize jsr310

---

web/src/main/java/org/jboss/pnc/causeway/rest/ReportsRestActivator.java

[NCL-6708] Activate JacksonProvider

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java

THis workarounds RHELBLD-15080

[NCLSUP-1067] Set proper Accept header in Url connection

---

application/pom.xml
core/pom.xml
pom.xml
rest/pom.xml
web/pom.xml

Update version to 3.0.0

---

pom.xml

Update pnc versions to latest

---

pom.xml

update to released pnc-api 3.0.4

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/SpecialImportFileGenerator.java

We use the default JDK HttpClient to download logs from PNC-Orch (via Bifrost redirect) to send to Brew.
The default HttpClient in the Java JDK has known issues with http2 and GOAWAY server messages.
(https://bugs.openjdk.org/browse/JDK-8335181?jql=text%20~%20%22httpclient%20goaway%22) that can be avoided by either using HTTP 1.1 only or using Apache HttpClient.
This commit attempts to resolve our GOAWAY errors by:
- switching to Apache Http Client 4.5
- the 4.5 version only supports HTTP 1.1, but future upgrades to v5.0 will enable HTTP 2 and also properly handle the GOAWAY messages from the server
- natively use the retries built-into Apache Http Client to retry a new request when we get GOAWAY messages
- Apache Http Client follows redirects automatically for GET requests, so we have …

[NCL-8784] Switch to apache http client to avoid GOAWAY

---

web/pom.xml
web/src/main/java/org/jboss/pnc/causeway/rest/ImportEndpoint.java

[NCL-8808] Log if userInitiator not set

---

pom.xml

Update the versions in pom.xml

---

pom.xml

Build a uber-jar for qauseway

---

pom.xml

Add the '/q/health/live' and the '/q/health/ready' endpoints that we use in Kubernetes to check if the app is up and running

Add health check

---

src/main/resources/application.yaml

Add example oidc config to hopefully activate oidc

---

src/main/resources/application.yaml
src/test/java/org/jboss/pnc/causeway/brewclient/TranslatorTest.java

Disable OIDC for test

---

pom.xml
src/test/java/org/jboss/pnc/causeway/MockOidcClient.java

Update qauseway to latest quarkus

---

core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClient.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java

Fix for reimport when deleted build is found

---

core/src/main/java/org/jboss/pnc/causeway/authentication/KeycloakClient.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClient.java
core/src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java
core/src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java
pom.xml
web/src/main/java/org/jboss/pnc/causeway/rest/ReportsRestActivator.java

Downgrade maven-formatter-plugin to 2.23.0 to compile with J11

---

pom.xml
src/main/java/org/jboss/pnc/causeway/brewclient/BrewClientImpl.java

Update pnc-common to 3.0.2 + formatting

---

pom.xml
src/main/templates/org/jboss/pnc/causeway/constants/BuildInformationConstants.java

Add version property + fix javadoc

---

pom.xml
src/main/resources/application.yaml

Add logging to kafka

---

pom.xml

Make causeway log in JSON

---

pom.xml
src/main/resources/application.yaml

This reverts commit 3f7e64824ac3d3997cdad6e4661e162cd1ae90e9.

Revert "Add logging to kafka"

---

src/main/java/org/jboss/pnc/causeway/brewclient/ImportFileGenerator.java

Fix NPE when sources are aready part of the build artifacts

---

pom.xml
src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslator.java
src/main/java/org/jboss/pnc/causeway/brewclient/BuildTranslatorImpl.java
src/main/java/org/jboss/pnc/causeway/ctl/ImportControllerImpl.java
src/main/java/org/jboss/pnc/causeway/impl/BurnAfterReadingFile.java
src/main/java/org/jboss/pnc/causeway/pncclient/PncClient.java
src/test/java/org/jboss/pnc/causeway/ctl/ImportControllerTest.java

Needs rebasing once #369 is merged

NCL-9177 Add ability to push RPMs

---

pom.xml

Update pnc common to 3.3.3
